name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    name: Run UI Tests
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Run tests on iPhone 15 Simulator with iOS 17.2
    - name: Run Tests on iPhone 15 Simulator (iOS 17.2)
      run: |
        xcodebuild test \
          -scheme 'UITestingSample' \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
